apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: intel-i
  labels:
    app: postgres-data
    app.kubernetes.io/part-of: intel-i
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: intel-i-local
  volumeName: intel-i-postgres
  resources:
    requests:
      storage: 20Gi
