apiVersion: v1
kind: PersistentVolume
metadata:
  name: intel-i-postgres
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: intel-i-local
  local:
    path: /var/lib/intel-i/postgres
  claimRef:
    namespace: intel-i
    name: postgres-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: intel-i/node
          operator: In
          values:
          - single-l40s
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: intel-i-redis
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: intel-i-local
  local:
    path: /var/lib/intel-i/redis
  claimRef:
    namespace: intel-i
    name: redis-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: intel-i/node
          operator: In
          values:
          - single-l40s
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: intel-i-kafka
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: intel-i-local
  local:
    path: /var/lib/intel-i/kafka
  claimRef:
    namespace: intel-i
    name: kafka-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: intel-i/node
          operator: In
          values:
          - single-l40s
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: intel-i-minio
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: intel-i-local
  local:
    path: /var/lib/intel-i/minio
  claimRef:
    namespace: intel-i
    name: minio-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: intel-i/node
          operator: In
          values:
          - single-l40s
