"""add persistent intelligence fields

Revision ID: 0613bd1b20fb
Revises: 2901f0dcb2ac
Create Date: 2026-08-23 15:19:57.728907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0613bd1b20fb'
down_revision: Union[str, Sequence[str], None] = '2901f0dcb2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
