"""
add vehicle watchlist alert fields

Revision ID: 438a1c72de3e
Revises: d1e7f5a9c2b4
Create Date: 2026-08-26 17:17:11.573196

Production-safe migration.

IMPORTANT:
- Existing watchlists table MUST NOT be dropped.
- Existing watchlist_entries table MUST NOT be dropped.
- Existing watchlist data MUST be preserved.
- Existing PostgreSQL indexes are handled safely.
- Migration is transactional under PostgreSQL.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ============================================================================
# ALEMBIC IDENTIFIERS
# ============================================================================

revision: str = "438a1c72de3e"

down_revision: Union[str, Sequence[str], None] = "d1e7f5a9c2b4"

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


# ============================================================================
# HELPERS
# ============================================================================


def _drop_index_if_exists(
    index_name: str,
    table_name: str,
) -> None:
    """
    Drop a PostgreSQL index only when it exists.

    This prevents migration failure when the index is absent because
    the existing INTEL-I database schema may differ slightly from the
    schema that originally generated the migration.
    """

    connection = op.get_bind()

    connection.execute(
        sa.text(
            f'DROP INDEX IF EXISTS "{index_name}"'
        )
    )


def _create_index_if_not_exists(
    index_name: str,
    table_name: str,
    columns: list[str],
) -> None:
    """
    Create a PostgreSQL index only when it does not already exist.
    """

    quoted_columns = ", ".join(
        f'"{column}"'
        for column in columns
    )

    connection = op.get_bind()

    connection.execute(
        sa.text(
            f"""
            CREATE INDEX IF NOT EXISTS "{index_name}"
            ON "{table_name}" ({quoted_columns})
            """
        )
    )


# ============================================================================
# UPGRADE
# ============================================================================


def upgrade() -> None:
    """
    Apply vehicle/watchlist alert index changes.

    Production safety rules:

    1. NEVER drop watchlists.
    2. NEVER drop watchlist_entries.
    3. NEVER remove existing watchlist data.
    4. Remove only obsolete alert indexes when present.
    5. Add required incident-evidence indexes.
    6. Add required person-watchlist-entry indexes.
    """

    # ========================================================================
    # IMPORTANT:
    #
    # The original autogenerated migration attempted to do:
    #
    #     DROP TABLE watchlists
    #     DROP TABLE watchlist_entries
    #
    # That is incorrect because those tables were already created by the
    # earlier watchlist migration:
    #
    #     a7c92f6e3b11
    #
    # Therefore the watchlist tables and ALL of their indexes are intentionally
    # left untouched here.
    # ========================================================================


    # ========================================================================
    # ALERT WATCHLIST INDEXES
    # ========================================================================
    #
    # These indexes are removed only if they actually exist.
    #
    # We do NOT touch the alerts table itself.
    # We do NOT drop any alert columns.
    # ========================================================================

    _drop_index_if_exists(
        "idx_alerts_watchlist_lookup",
        "alerts",
    )

    _drop_index_if_exists(
        "ix_alerts_watchlist_category",
        "alerts",
    )

    _drop_index_if_exists(
        "ix_alerts_watchlist_match_confidence",
        "alerts",
    )

    _drop_index_if_exists(
        "ix_alerts_watchlist_match_type",
        "alerts",
    )

    _drop_index_if_exists(
        "ix_alerts_watchlist_status",
        "alerts",
    )

    _drop_index_if_exists(
        "ix_alerts_watchlist_version",
        "alerts",
    )


    # ========================================================================
    # INCIDENT EVIDENCE INDEXES
    # ========================================================================
    #
    # IF NOT EXISTS prevents failure when one or more indexes are already
    # present in the existing database.
    # ========================================================================

    _create_index_if_not_exists(
        "ix_incident_evidence_alert_id",
        "incident_evidence",
        ["alert_id"],
    )

    _create_index_if_not_exists(
        "ix_incident_evidence_created_at",
        "incident_evidence",
        ["created_at"],
    )

    _create_index_if_not_exists(
        "ix_incident_evidence_evidence_type",
        "incident_evidence",
        ["evidence_type"],
    )

    _create_index_if_not_exists(
        "ix_incident_evidence_id",
        "incident_evidence",
        ["id"],
    )

    _create_index_if_not_exists(
        "ix_incident_evidence_incident_id",
        "incident_evidence",
        ["incident_id"],
    )

    _create_index_if_not_exists(
        "ix_incident_evidence_object_reference",
        "incident_evidence",
        ["object_reference"],
    )

    _create_index_if_not_exists(
        "ix_incident_evidence_object_type",
        "incident_evidence",
        ["object_type"],
    )

    _create_index_if_not_exists(
        "ix_incident_evidence_snapshot_id",
        "incident_evidence",
        ["snapshot_id"],
    )

    _create_index_if_not_exists(
        "ix_incident_evidence_user_id",
        "incident_evidence",
        ["user_id"],
    )


    # ========================================================================
    # PERSON WATCHLIST ENTRY INDEXES
    # ========================================================================
    #
    # Again, IF NOT EXISTS protects the existing production database.
    # ========================================================================

    _create_index_if_not_exists(
        "ix_person_watchlist_entries_category",
        "person_watchlist_entries",
        ["category"],
    )

    _create_index_if_not_exists(
        "ix_person_watchlist_entries_created_at",
        "person_watchlist_entries",
        ["created_at"],
    )

    _create_index_if_not_exists(
        "ix_person_watchlist_entries_id",
        "person_watchlist_entries",
        ["id"],
    )

    _create_index_if_not_exists(
        "ix_person_watchlist_entries_status",
        "person_watchlist_entries",
        ["status"],
    )

    _create_index_if_not_exists(
        "ix_person_watchlist_entries_updated_at",
        "person_watchlist_entries",
        ["updated_at"],
    )

    _create_index_if_not_exists(
        "ix_person_watchlist_entries_user_id",
        "person_watchlist_entries",
        ["user_id"],
    )


# ============================================================================
# DOWNGRADE
# ============================================================================


def downgrade() -> None:
    """
    Safely revert the changes introduced by this migration.

    IMPORTANT:
    - Existing watchlists are NOT dropped.
    - Existing watchlist_entries are NOT dropped.
    - Existing watchlist data is preserved.
    """

    # ========================================================================
    # REMOVE INDEXES CREATED BY THIS MIGRATION
    # ========================================================================

    _drop_index_if_exists(
        "ix_person_watchlist_entries_user_id",
        "person_watchlist_entries",
    )

    _drop_index_if_exists(
        "ix_person_watchlist_entries_updated_at",
        "person_watchlist_entries",
    )

    _drop_index_if_exists(
        "ix_person_watchlist_entries_status",
        "person_watchlist_entries",
    )

    _drop_index_if_exists(
        "ix_person_watchlist_entries_id",
        "person_watchlist_entries",
    )

    _drop_index_if_exists(
        "ix_person_watchlist_entries_created_at",
        "person_watchlist_entries",
    )

    _drop_index_if_exists(
        "ix_person_watchlist_entries_category",
        "person_watchlist_entries",
    )


    # ========================================================================
    # INCIDENT EVIDENCE INDEXES
    # ========================================================================

    _drop_index_if_exists(
        "ix_incident_evidence_user_id",
        "incident_evidence",
    )

    _drop_index_if_exists(
        "ix_incident_evidence_snapshot_id",
        "incident_evidence",
    )

    _drop_index_if_exists(
        "ix_incident_evidence_object_type",
        "incident_evidence",
    )

    _drop_index_if_exists(
        "ix_incident_evidence_object_reference",
        "incident_evidence",
    )

    _drop_index_if_exists(
        "ix_incident_evidence_incident_id",
        "incident_evidence",
    )

    _drop_index_if_exists(
        "ix_incident_evidence_id",
        "incident_evidence",
    )

    _drop_index_if_exists(
        "ix_incident_evidence_evidence_type",
        "incident_evidence",
    )

    _drop_index_if_exists(
        "ix_incident_evidence_created_at",
        "incident_evidence",
    )

    _drop_index_if_exists(
        "ix_incident_evidence_alert_id",
        "incident_evidence",
    )


    # ========================================================================
    # RESTORE ALERT WATCHLIST INDEXES
    # ========================================================================
    #
    # These were the indexes removed by upgrade().
    #
    # They are recreated only when absent.
    # ========================================================================

    _create_index_if_not_exists(
        "ix_alerts_watchlist_version",
        "alerts",
        ["watchlist_version"],
    )

    _create_index_if_not_exists(
        "ix_alerts_watchlist_status",
        "alerts",
        ["watchlist_status"],
    )

    _create_index_if_not_exists(
        "ix_alerts_watchlist_match_type",
        "alerts",
        ["watchlist_match_type"],
    )

    _create_index_if_not_exists(
        "ix_alerts_watchlist_match_confidence",
        "alerts",
        ["watchlist_match_confidence"],
    )

    _create_index_if_not_exists(
        "ix_alerts_watchlist_category",
        "alerts",
        ["watchlist_category"],
    )

    _create_index_if_not_exists(
        "idx_alerts_watchlist_lookup",
        "alerts",
        [
            "user_id",
            "cam_id",
            "rule",
            "track_id",
            "watchlist_entry_id",
            "created_at",
        ],
    )