"""sync INTEL-I production schema

Revision ID: 690ae3d7577b
Revises: e5a7c9d2f410
Create Date: 2026-09-03 11:06:53.237916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '690ae3d7577b'
down_revision: Union[str, Sequence[str], None] = 'e5a7c9d2f410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('camera_health', 'frame_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_camera_health_camera_id'), 'camera_health', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_health_created_at'), 'camera_health', ['created_at'], unique=False)
    op.create_index(op.f('ix_camera_health_id'), 'camera_health', ['id'], unique=False)
    op.create_index(op.f('ix_camera_health_state'), 'camera_health', ['state'], unique=False)
    op.alter_column('camera_time_sync', 'sync_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('camera_time_sync', 'sync_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('camera_time_sync', 'sample_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('camera_time_sync', 'source_timestamp_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_camera_time_sync_status'), table_name='camera_time_sync')
    op.drop_index(op.f('idx_camera_time_sync_updated'), table_name='camera_time_sync')
    op.drop_constraint(op.f('uq_camera_time_sync_camera'), 'camera_time_sync', type_='unique')
    op.create_index(op.f('ix_camera_time_sync_camera_id'), 'camera_time_sync', ['camera_id'], unique=True)
    op.create_index(op.f('ix_camera_time_sync_created_at'), 'camera_time_sync', ['created_at'], unique=False)
    op.create_index(op.f('ix_camera_time_sync_id'), 'camera_time_sync', ['id'], unique=False)
    op.create_index(op.f('ix_camera_time_sync_sync_status'), 'camera_time_sync', ['sync_status'], unique=False)
    op.create_index(op.f('ix_camera_time_sync_updated_at'), 'camera_time_sync', ['updated_at'], unique=False)
    op.drop_column('correlation_decisions', 'evidence_metadata')
    op.alter_column('evidence_hashes', 'algorithm',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('evidence_hashes', 'is_original',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_evidence_hash_sha256'), table_name='evidence_hashes')
    op.drop_constraint(op.f('uq_evidence_hash_key'), 'evidence_hashes', type_='unique')
    op.create_index(op.f('ix_evidence_hashes_created_at'), 'evidence_hashes', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_hashes_evidence_key'), 'evidence_hashes', ['evidence_key'], unique=True)
    op.create_index(op.f('ix_evidence_hashes_id'), 'evidence_hashes', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_hashes_sha256'), 'evidence_hashes', ['sha256'], unique=False)
    op.create_index(op.f('ix_investigation_summaries_id'), 'investigation_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_person_correlation_decisions_id'), 'person_correlation_decisions', ['id'], unique=False)
    op.alter_column('snapshots', 'is_original',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stream_metrics', 'decoded_frames',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stream_metrics', 'processed_frames',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stream_metrics', 'dropped_frames',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stream_metrics', 'queue_depth',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stream_metrics', 'queue_capacity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stream_metrics', 'reconnect_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_stream_metrics_camera_time'), table_name='stream_metrics')
    op.create_index(op.f('ix_stream_metrics_camera_id'), 'stream_metrics', ['camera_id'], unique=False)
    op.create_index(op.f('ix_stream_metrics_created_at'), 'stream_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_stream_metrics_id'), 'stream_metrics', ['id'], unique=False)
    op.alter_column('system_events', 'severity',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_system_events_component'), 'system_events', ['component'], unique=False)
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_id'), 'system_events', ['id'], unique=False)
    op.create_index(op.f('ix_system_events_severity'), 'system_events', ['severity'], unique=False)
    op.alter_column('watchlist_entries', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('watchlist_entries', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('watchlist_entries', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('watchlist_entries', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_watchlist_versions_created_at'), 'watchlist_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_watchlist_versions_id'), 'watchlist_versions', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_versions_watchlist_id'), 'watchlist_versions', ['watchlist_id'], unique=False)
    op.alter_column('watchlists', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlists', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_watchlist_versions_watchlist_id'), table_name='watchlist_versions')
    op.drop_index(op.f('ix_watchlist_versions_id'), table_name='watchlist_versions')
    op.drop_index(op.f('ix_watchlist_versions_created_at'), table_name='watchlist_versions')
    op.alter_column('watchlist_entries', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('watchlist_entries', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'HIGH'::character varying"),
               existing_nullable=False)
    op.alter_column('watchlist_entries', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=False)
    op.alter_column('watchlist_entries', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'SUSPICIOUS'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_system_events_severity'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_component'), table_name='system_events')
    op.alter_column('system_events', 'severity',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'INFO'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_stream_metrics_id'), table_name='stream_metrics')
    op.drop_index(op.f('ix_stream_metrics_created_at'), table_name='stream_metrics')
    op.drop_index(op.f('ix_stream_metrics_camera_id'), table_name='stream_metrics')
    op.create_index(op.f('idx_stream_metrics_camera_time'), 'stream_metrics', ['camera_id', 'created_at'], unique=False)
    op.alter_column('stream_metrics', 'reconnect_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('stream_metrics', 'queue_capacity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('stream_metrics', 'queue_depth',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('stream_metrics', 'dropped_frames',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('stream_metrics', 'processed_frames',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('stream_metrics', 'decoded_frames',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('snapshots', 'is_original',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_person_correlation_decisions_id'), table_name='person_correlation_decisions')
    op.drop_index(op.f('ix_investigation_summaries_id'), table_name='investigation_summaries')
    op.drop_index(op.f('ix_evidence_hashes_sha256'), table_name='evidence_hashes')
    op.drop_index(op.f('ix_evidence_hashes_id'), table_name='evidence_hashes')
    op.drop_index(op.f('ix_evidence_hashes_evidence_key'), table_name='evidence_hashes')
    op.drop_index(op.f('ix_evidence_hashes_created_at'), table_name='evidence_hashes')
    op.create_unique_constraint(op.f('uq_evidence_hash_key'), 'evidence_hashes', ['evidence_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_evidence_hash_sha256'), 'evidence_hashes', ['sha256'], unique=False)
    op.alter_column('evidence_hashes', 'is_original',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('evidence_hashes', 'algorithm',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'SHA-256'::character varying"),
               existing_nullable=False)
    op.add_column('correlation_decisions', sa.Column('evidence_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_camera_time_sync_updated_at'), table_name='camera_time_sync')
    op.drop_index(op.f('ix_camera_time_sync_sync_status'), table_name='camera_time_sync')
    op.drop_index(op.f('ix_camera_time_sync_id'), table_name='camera_time_sync')
    op.drop_index(op.f('ix_camera_time_sync_created_at'), table_name='camera_time_sync')
    op.drop_index(op.f('ix_camera_time_sync_camera_id'), table_name='camera_time_sync')
    op.create_unique_constraint(op.f('uq_camera_time_sync_camera'), 'camera_time_sync', ['camera_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_camera_time_sync_updated'), 'camera_time_sync', ['updated_at'], unique=False)
    op.create_index(op.f('idx_camera_time_sync_status'), 'camera_time_sync', ['sync_status'], unique=False)
    op.alter_column('camera_time_sync', 'source_timestamp_available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('camera_time_sync', 'sample_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('camera_time_sync', 'sync_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'ARRIVAL_TIME'::character varying"),
               existing_nullable=False)
    op.alter_column('camera_time_sync', 'sync_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'ESTIMATED'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_camera_health_state'), table_name='camera_health')
    op.drop_index(op.f('ix_camera_health_id'), table_name='camera_health')
    op.drop_index(op.f('ix_camera_health_created_at'), table_name='camera_health')
    op.drop_index(op.f('ix_camera_health_camera_id'), table_name='camera_health')
    op.alter_column('camera_health', 'frame_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    # ### end Alembic commands ###
