apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: intel-i-api
  namespace: intel-i
  labels:
    monitoring: intel-i
spec:
  namespaceSelector:
    matchNames:
    - intel-i
  selector:
    matchLabels:
      app: intel-i-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
